{
    "formtabs": [
        {
            "MIGX_id": 5,
            "caption": "Improvement",
            "print_before_tabs": "0",
            "fields": [
                {
                    "MIGX_id": 11,
                    "field": "improvements",
                    "caption": "Nature",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "listbox",
                    "validation": "",
                    "configs": {
                        "listWidth": "500",
                        "typeAhead": "true",
                        "typeAheadDelay": "250"
                    },
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "@CHUNK tvSelectInputOption@StatusImprovement",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 1
                },
                {
                    "MIGX_id": 12,
                    "field": "title",
                    "caption": "Title",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "text",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 2
                },
                {
                    "MIGX_id": 13,
                    "field": "content",
                    "caption": "Explanation",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "richtext",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 2
                }
            ],
            "pos": 1
        },
        {
            "MIGX_id": 6,
            "caption": "Properties",
            "print_before_tabs": "0",
            "fields": [
                {
                    "MIGX_id": 14,
                    "field": "complexity",
                    "caption": "Complexity",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "option",
                    "validation": "",
                    "configs": {
                        "columns": "20"
                    },
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "@CHUNK tvSelectFibonacci",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 14
                },
                {
                    "MIGX_id": 15,
                    "field": "priority",
                    "caption": "Priority",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "option",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "@CHUNK tvSelectInputOption@ImprovementPriority",
                    "default": "2",
                    "useDefaultIfEmpty": "true",
                    "pos": 15
                },
                {
                    "MIGX_id": 16,
                    "field": "user_id",
                    "caption": "Assigned to",
                    "description": "Who is best suited to look at this improvement?",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "superboxselect",
                    "validation": "",
                    "configs": {
                        "selectType": "users",
                        "maxElements": "1",
                        "allowBlank": "1",
                        "depth": "10",
                        "limitRelatedContext": "0",
                        "pageSize": "10"
                    },
                    "restrictive_condition": "",
                    "display": "",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 16
                },
                {
                    "MIGX_id": 96,
                    "field": "type",
                    "caption": "Type",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "text",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "none",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "improvement",
                    "useDefaultIfEmpty": "0",
                    "pos": 96
                },
                {
                    "MIGX_id": 97,
                    "field": "createdby",
                    "caption": "Author",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "number",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "none",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 97
                },
                {
                    "MIGX_id": 98,
                    "field": "createdon",
                    "caption": "Date",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "date",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "none",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 98
                },
                {
                    "MIGX_id": 99,
                    "field": "id",
                    "caption": "ID",
                    "description": "",
                    "description_is_code": "0",
                    "inputTV": "",
                    "inputTVtype": "number",
                    "validation": "",
                    "configs": "",
                    "restrictive_condition": "",
                    "display": "none",
                    "sourceFrom": "config",
                    "sources": "",
                    "inputOptionValues": "",
                    "default": "",
                    "useDefaultIfEmpty": "0",
                    "pos": 99
                }
            ],
            "pos": 2
        }
    ],
    "contextmenus": "update||duplicate||recall_remove_delete",
    "actionbuttons": "addItem||bulk||toggletrash||emptyTrash",
    "columnbuttons": "",
    "filters": "",
    "extended": {
        "migx_add": "Add improvement",
        "disable_add_item": "",
        "add_items_directly": "",
        "formcaption": "",
        "update_win_title": "Edit improvement",
        "win_id": 30,
        "maxRecords": "",
        "addNewItemAt": "top",
        "multiple_formtabs": "",
        "multiple_formtabs_label": "",
        "multiple_formtabs_field": "",
        "multiple_formtabs_optionstext": "",
        "multiple_formtabs_optionsvalue": "",
        "actionbuttonsperrow": 4,
        "winbuttonslist": "",
        "extrahandlers": "",
        "filtersperrow": 4,
        "packageName": "romanescobackyard",
        "classname": "rmNoteImprovement",
        "task": "",
        "getlistsort": "createdon",
        "getlistsortdir": "DESC",
        "sortconfig": "",
        "gridpagesize": "",
        "use_custom_prefix": "0",
        "prefix": "",
        "grid": "",
        "gridload_mode": 1,
        "check_resid": 1,
        "check_resid_TV": "",
        "join_alias": "",
        "has_jointable": "yes",
        "getlistwhere": "",
        "joins": "",
        "hooksnippets": "",
        "cmpmaincaption": "Backyard tool shed",
        "cmptabcaption": "Content improvements",
        "cmptabdescription": "The items in this list are collected from the Status tab on each page. It is recommended that you add improvements on the page itself and use this list for convenience only. You can sort improvements on priority for example, or filter the ones assigned to you.",
        "cmptabcontroller": "",
        "winbuttons": "",
        "onsubmitsuccess": "",
        "submitparams": ""
    },
    "columns": [
        {
            "MIGX_id": 1,
            "header": "Area",
            "dataIndex": "improvements",
            "width": 30,
            "sortable": true,
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "this.renderChunk",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "[[Rowboat? &table=`modx_romanesco_options` &tpl=`rawName` &where=`{\"id:=\":\"[[+improvements]]\"}`]]",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 2,
            "header": "Title",
            "dataIndex": "title",
            "width": 50,
            "sortable": "false",
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "]",
            "renderoptions": "",
            "editor": "this.textEditor"
        },
        {
            "MIGX_id": 3,
            "header": "Explanation",
            "dataIndex": "content",
            "width": 80,
            "sortable": "false",
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "",
            "renderoptions": "",
            "editor": "this.textEditor"
        },
        {
            "MIGX_id": 4,
            "header": "Author",
            "dataIndex": "author_id",
            "width": 30,
            "sortable": true,
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "this.renderChunk",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "[[+author_id:userinfo=`username`]]",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 5,
            "header": "Assigned to",
            "dataIndex": "user_id",
            "width": 30,
            "sortable": true,
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "this.renderChunk",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "[[+user_id:userinfo=`username`]]",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 6,
            "header": "Created on",
            "dataIndex": "createdon",
            "width": 30,
            "sortable": 1,
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "this.renderChunk",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "[[+createdon:date=`[[++romanesco.date_format_short]]`]]",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 7,
            "header": "Priority",
            "dataIndex": "priority",
            "width": 20,
            "sortable": true,
            "show_in_grid": 1,
            "customrenderer": "",
            "renderer": "",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 98,
            "header": "ID",
            "dataIndex": "id",
            "width": 10,
            "sortable": true,
            "show_in_grid": 0,
            "customrenderer": "",
            "renderer": "",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "",
            "renderoptions": "",
            "editor": ""
        },
        {
            "MIGX_id": 99,
            "header": "deleted",
            "dataIndex": "deleted",
            "width": 10,
            "sortable": true,
            "show_in_grid": 0,
            "customrenderer": "",
            "renderer": "",
            "clickaction": "",
            "selectorconfig": "",
            "renderchunktpl": "",
            "renderoptions": "",
            "editor": ""
        }
    ],
    "category": ""
}